export const FIRST_SEO_PAGE_PRODUCTION_WAVE_2026_07_13 = {
  provenance: {
    demandSource: 'gotoflow_demand_master_v2',
    demandShortlist: '20 owner-selected candidates from the full demand master',
    analyzedAt: '2026-07-13',
    productionHost: 'https://gotoflow.io',
    startingHead: 'cdb4862d4b4e92d462ce906764eba7330ee397d5',
    remoteMainAtAudit: 'cdb4862d4b4e92d462ce906764eba7330ee397d5',
    branchAtAudit: 'main',
    createdBy: 'Codex SEO Pages Engine planning audit',
    scope: 'Planning, intent ownership, cannibalization, and production briefs only. No runtime routes, sitemap entries, assets, page JSX, or article drafts.',
  },

  repositoryAudit: {
    protectedRouteOwners: [
      '/ru/ai-generator-karuselej',
      '/ru/generator-karuselej-instagram',
      '/ru/ii-generator-karuseley',
      '/ru/generator-kontenta',
      '/ru/ii-generator-kontenta',
      '/ru/generator-postov-instagram',
      '/ru/ii-generator-postov-dlya-instagram',
      '/ru/generator-karuselej-linkedin',
      '/ru/ii-generator-postov-dlya-linkedin',
    ],
    seoPageRegistryOwnersReviewed: [
      '/ru/templates/instagram-carousel',
      '/ru/generator-karuseley',
      '/ru/ii-generator-karuseley',
      '/ru/instagram-carousel-generator',
      '/ru/instagram-post-generator',
      '/ru/vk-post-generator',
      '/ru/telegram-post-generator',
      '/ru/linkedin-carousel-generator',
    ],
    canonicalReferencePage: '/ru/templates/instagram-carousel',
    appRouteInventorySource: 'src/App.jsx',
    protectedRoutesSource: 'src/content/seoPages/protectedRoutes.js',
    productTruthSource: 'src/content/seoPages/productTruthRegistry.js',
    blogIntentSource: 'src/content/blog/intent-map.json',
    planningCanonicalLocation: 'src/content/seoPages/planning/',
    sitemapChanged: false,
    runtimeChanged: false,
  },

  productTruthSummary: {
    confirmed: [
      'AI carousel creation',
      'template carousel creation',
      'animated carousel creation',
      'seamless carousel creation',
      'dozens of templates',
      'ready in 60 seconds',
      'Instagram supports up to 20 photos or videos',
      'GoToFlow creates up to 10 slides',
      'recommended carousel range is 5-10 slides',
      'topic, text, link, video, PDF, and voice inputs',
      'text editing and regeneration',
      'AI style, custom prompt, template, background, character, and CTA settings',
      'manual editing',
      '4:5, 1:1, and 9:16 formats',
    ],
    partialOrUnsupported: [
      'Photo-only carousel generation is not listed as a confirmed input in the SEO Product Truth Registry; support it through existing technical articles until product workflow is explicitly confirmed.',
      'Direct publishing to social platforms is not supported and must not be claimed.',
      'Guaranteed performance, reach, saves, followers, or revenue claims are forbidden.',
    ],
  },

  decisionMatrix: [
    {
      candidate_id: '01',
      candidate_topic: 'Генератор каруселей для Instagram',
      primary_query: 'генератор каруселей для instagram',
      user_job: 'Создать Instagram-карусель с готовой структурой, слайдами, визуалом и CTA.',
      intent_type: 'tool',
      existing_owner: '/ru/generator-karuselej-instagram',
      existing_supporting_pages: ['/ru/blog/kak-sdelat-karusel-dlya-instagram-s-ii', '/ru/blog/karusel-dlya-instagram', '/ru/blog/razmer-karuseli-v-instagram'],
      overlap_routes: ['/ru/ai-generator-karuselej', '/ru/ii-generator-karuseley', '/ru/templates/instagram-carousel', '/ru/instagram-carousel-generator'],
      cannibalization_risk: 'medium',
      product_capability: 'confirmed',
      decision: 'STRENGTHEN_EXISTING_OWNER',
      target_route: '/ru/generator-karuselej-instagram',
      page_variant: 'commercial_tool',
      unique_angle: 'Instagram-specific generator owner for creating a ready carousel in GoToFlow.',
      boundary: 'Do not own template discovery, generic AI carousel, examples, prompts, or technical publishing-size guidance.',
      internal_links_in: ['/ru/templates/instagram-carousel', '/ru/blog/kak-sdelat-karusel-dlya-instagram-s-ii', '/ru/blog/karusel-dlya-instagram'],
      internal_links_out: ['/ru/templates/instagram-carousel', '/ru/blog/razmer-karuseli-v-instagram', '/ru/blog/prompty-dlya-karuseley-v-instagram'],
      supporting_article_needed: 'no',
      reason: 'Exact protected route owner exists and should be strengthened instead of duplicated by a registry URL.',
      priority: 'P0',
      production_wave: 'WAVE_1',
    },
    {
      candidate_id: '02',
      candidate_topic: 'Карусели для Instagram — создать и оформить',
      primary_query: 'создать карусель instagram',
      user_job: 'Понять как собрать и оформить Instagram-карусель без ручной сборки с нуля.',
      intent_type: 'commercial',
      existing_owner: '/ru/generator-karuselej-instagram',
      existing_supporting_pages: ['/ru/blog/kak-sdelat-karusel-dlya-instagram-s-ii', '/ru/blog/chto-takoe-karusel-v-instagram', '/ru/blog/karusel-dlya-instagram'],
      overlap_routes: ['/ru/templates/instagram-carousel', '/ru/ai-generator-karuselej'],
      cannibalization_risk: 'high',
      product_capability: 'confirmed',
      decision: 'STRENGTHEN_EXISTING_OWNER',
      target_route: '/ru/generator-karuselej-instagram',
      page_variant: 'commercial_tool',
      unique_angle: 'Creation-and-formatting section inside the Instagram generator owner.',
      boundary: 'No separate route for a near-duplicate create/design query.',
      internal_links_in: ['/ru/blog/kak-sdelat-karusel-dlya-instagram-s-ii', '/ru/blog/chto-takoe-karusel-v-instagram'],
      internal_links_out: ['/ru/templates/instagram-carousel', '/ru/blog/primery-karuseley-instagram'],
      supporting_article_needed: 'no',
      reason: 'The query is a close synonym of the Instagram generator job and would compete with the protected owner.',
      priority: 'P0',
      production_wave: 'WAVE_2',
    },
    {
      candidate_id: '03',
      candidate_topic: 'Генератор каруселей онлайн',
      primary_query: 'генератор каруселей онлайн',
      user_job: 'Найти online-инструмент, чтобы создать карусель без локального дизайнера или сложного редактора.',
      intent_type: 'tool',
      existing_owner: '/ru/ai-generator-karuselej',
      existing_supporting_pages: ['/ru/blog/konstruktor-karuseley-onlayn', '/ru/blog/luchshie-ai-generatory-karuselej'],
      overlap_routes: ['/ru/ii-generator-karuseley', '/ru/generator-karuselej-instagram', '/ru/generator-karuseley'],
      cannibalization_risk: 'high',
      product_capability: 'confirmed',
      decision: 'STRENGTHEN_EXISTING_OWNER',
      target_route: '/ru/ai-generator-karuselej',
      page_variant: 'commercial_tool',
      unique_angle: 'Online tool framing inside the generic AI carousel owner.',
      boundary: 'Do not create a generic online generator URL while the protected AI carousel route owns this commercial job.',
      internal_links_in: ['/ru/blog/konstruktor-karuseley-onlayn', '/ru/blog/luchshie-ai-generatory-karuselej'],
      internal_links_out: ['/ru/generator-karuselej-instagram', '/ru/generator-karuselej-linkedin'],
      supporting_article_needed: 'no',
      reason: 'Existing protected route and article coverage already cover the online-tool intent.',
      priority: 'P1',
      production_wave: 'WAVE_2',
    },
    {
      candidate_id: '04',
      candidate_topic: 'ИИ-генератор каруселей',
      primary_query: 'ии генератор каруселей',
      user_job: 'Создать карусель с помощью ИИ из темы, текста, ссылки, видео, PDF или голосового.',
      intent_type: 'tool',
      existing_owner: '/ru/ii-generator-karuseley',
      existing_supporting_pages: ['/ru/blog/ii-dlya-karuseley', '/ru/blog/tekst-v-karusel-neyroset', '/ru/blog/luchshie-ai-generatory-karuselej'],
      overlap_routes: ['/ru/ai-generator-karuselej', '/ru/generator-karuselej-instagram', '/ru/generator-karuseley'],
      cannibalization_risk: 'medium',
      product_capability: 'confirmed',
      decision: 'STRENGTHEN_EXISTING_OWNER',
      target_route: '/ru/ii-generator-karuseley',
      page_variant: 'commercial_tool',
      unique_angle: 'AI-first carousel creation route with source inputs and editable ready result.',
      boundary: 'Do not replace platform-specific Instagram/LinkedIn owners or prompt-library articles.',
      internal_links_in: ['/ru/blog/ii-dlya-karuseley', '/ru/blog/luchshie-ai-generatory-karuselej', '/ru/blog/tekst-v-karusel-neyroset'],
      internal_links_out: ['/ru/generator-karuselej-instagram', '/ru/generator-karuselej-linkedin', '/ru/blog/prompty-dlya-karuseley-v-instagram'],
      supporting_article_needed: 'no',
      reason: 'Protected historical product route owns this exact high-commercial AI generator intent.',
      priority: 'P0',
      production_wave: 'WAVE_1',
    },
    {
      candidate_id: '05',
      candidate_topic: 'Приложения и сервисы для создания каруселей',
      primary_query: 'сервисы для создания каруселей',
      user_job: 'Сравнить способы и сервисы для создания каруселей и выбрать подходящий workflow.',
      intent_type: 'comparison',
      existing_owner: '/ru/blog/luchshie-ai-generatory-karuselej',
      existing_supporting_pages: ['/ru/blog/luchshie-ai-generatory-karuselej', '/ru/blog/dizayn-karuseley-neyroset-vs-canva'],
      overlap_routes: ['/ru/alternatives/*', '/ru/ii-generator-karuseley'],
      cannibalization_risk: 'medium',
      product_capability: 'partial',
      decision: 'SUPPORT_WITH_EXISTING_ARTICLES',
      target_route: '/ru/alternatives/servisy-dlya-sozdaniya-karuseley',
      page_variant: 'alternative_page',
      unique_angle: 'Commercial comparison page only after fresh competitor/facts validation.',
      boundary: 'Existing article remains the informational review; page must not make stale or unsupported competitor claims.',
      internal_links_in: ['/ru/blog/luchshie-ai-generatory-karuselej', '/ru/blog/dizayn-karuseley-neyroset-vs-canva'],
      internal_links_out: ['/ru/ii-generator-karuseley', '/ru/templates/instagram-carousel'],
      supporting_article_needed: 'no',
      reason: 'Demand is valid, but comparison facts are freshness-sensitive and should be produced after a separate competitor verification pass.',
      priority: 'P1',
      production_wave: 'WAVE_2',
    },
    {
      candidate_id: '06',
      candidate_topic: 'Создать бесшовную карусель Instagram',
      primary_query: 'создать бесшовную карусель instagram',
      user_job: 'Создать seamless Instagram carousel in GoToFlow without manual panoramic slicing as the main workflow.',
      intent_type: 'feature',
      existing_owner: 'none',
      existing_supporting_pages: ['/ru/blog/besshovnaya-karusel-v-instagram', '/ru/blog/kak-narezat-foto-dlya-karuseli'],
      overlap_routes: ['/ru/generator-karuselej-instagram', '/ru/templates/instagram-carousel'],
      cannibalization_risk: 'low',
      product_capability: 'confirmed',
      decision: 'CREATE_NEW_PAGE',
      target_route: '/ru/use-cases/besshovnaya-karusel-instagram',
      page_variant: 'use_case_page',
      unique_angle: 'Product feature page for creating seamless carousel output in GoToFlow.',
      boundary: 'Do not become a technical panorama cutting guide; that stays with the blog article.',
      internal_links_in: ['/ru/blog/besshovnaya-karusel-v-instagram', '/ru/blog/kak-narezat-foto-dlya-karuseli', '/ru/generator-karuselej-instagram'],
      internal_links_out: ['/ru/generator-karuselej-instagram', '/ru/blog/besshovnaya-karusel-v-instagram', '/ru/blog/razmer-karuseli-v-instagram'],
      supporting_article_needed: 'no',
      reason: 'Seamless carousel is confirmed in Product Truth and has a distinct commercial feature job.',
      priority: 'P0',
      production_wave: 'WAVE_1',
    },
    {
      candidate_id: '07',
      candidate_topic: 'Создать карусель из текста',
      primary_query: 'текст в карусель',
      user_job: 'Turn an existing text, note, article, or тезисы into a carousel.',
      intent_type: 'feature',
      existing_owner: '/ru/blog/tekst-v-karusel-neyroset',
      existing_supporting_pages: ['/ru/blog/tekst-v-karusel-neyroset', '/ru/blog/kak-napisat-tekst-dlya-karuseli-s-ii'],
      overlap_routes: ['/ru/ii-generator-karuseley', '/ru/ai-generator-karuselej'],
      cannibalization_risk: 'low',
      product_capability: 'confirmed',
      decision: 'CREATE_NEW_PAGE',
      target_route: '/ru/use-cases/tekst-v-karusel',
      page_variant: 'use_case_page',
      unique_angle: 'Commercial input-source page for text-to-ready-carousel workflow.',
      boundary: 'The existing article keeps the educational how-to and prompt explanation.',
      internal_links_in: ['/ru/blog/tekst-v-karusel-neyroset', '/ru/ii-generator-karuseley'],
      internal_links_out: ['/ru/ii-generator-karuseley', '/ru/blog/tekst-v-karusel-neyroset', '/ru/blog/chitabelnost-teksta-v-karuselyah'],
      supporting_article_needed: 'no',
      reason: 'Text input is confirmed and the transactional job is distinct from the informational article.',
      priority: 'P0',
      production_wave: 'WAVE_1',
    },
    {
      candidate_id: '08',
      candidate_topic: 'Создать карусель из фото',
      primary_query: 'создать карусель из фото',
      user_job: 'Use photos or a panoramic image as source material for carousel slides.',
      intent_type: 'feature',
      existing_owner: '/ru/blog/kak-narezat-foto-dlya-karuseli',
      existing_supporting_pages: ['/ru/blog/kak-narezat-foto-dlya-karuseli', '/ru/blog/gorizontalnye-i-vertikalnye-foto-v-karuseli', '/ru/blog/pochemu-instagram-obrezaet-foto-v-karuseli'],
      overlap_routes: ['/ru/use-cases/besshovnaya-karusel-instagram', '/ru/generator-karuselej-instagram'],
      cannibalization_risk: 'medium',
      product_capability: 'partial',
      decision: 'HOLD',
      target_route: '/ru/use-cases/foto-v-karusel',
      page_variant: 'use_case_page',
      unique_angle: 'Potential photo-input workflow only after Product Truth confirms image/photo input as a first-class source.',
      boundary: 'Do not claim photo upload, automatic slicing, or direct panorama editing until confirmed.',
      internal_links_in: ['/ru/blog/kak-narezat-foto-dlya-karuseli'],
      internal_links_out: ['/ru/blog/besshovnaya-karusel-v-instagram', '/ru/blog/razmer-karuseli-v-instagram'],
      supporting_article_needed: 'no',
      reason: 'Current Product Truth confirms topic/text/link/video/PDF/voice inputs, not standalone photo input.',
      priority: 'HOLD',
      production_wave: 'NONE',
    },
    {
      candidate_id: '09',
      candidate_topic: 'Создать карусель из видео',
      primary_query: 'создать карусель из видео',
      user_job: 'Turn a video, Reels, webinar, or script into carousel slides.',
      intent_type: 'feature',
      existing_owner: '/ru/blog/kak-sdelat-karusel-iz-video-s-ii',
      existing_supporting_pages: ['/ru/blog/kak-sdelat-karusel-iz-video-s-ii', '/ru/blog/kak-peredelat-youtube-v-karusel-linkedin'],
      overlap_routes: ['/ru/ii-generator-karuseley', '/ru/generator-karuselej-linkedin'],
      cannibalization_risk: 'low',
      product_capability: 'confirmed',
      decision: 'CREATE_NEW_PAGE',
      target_route: '/ru/use-cases/video-v-karusel',
      page_variant: 'use_case_page',
      unique_angle: 'Commercial video-input page for turning existing video into a ready carousel.',
      boundary: 'Do not become a long-form repurposing guide; article owns the how-to detail.',
      internal_links_in: ['/ru/blog/kak-sdelat-karusel-iz-video-s-ii', '/ru/ii-generator-karuseley'],
      internal_links_out: ['/ru/ii-generator-karuseley', '/ru/blog/kak-sdelat-karusel-iz-video-s-ii', '/ru/blog/kak-peredelat-youtube-v-karusel-linkedin'],
      supporting_article_needed: 'no',
      reason: 'Video input is confirmed and has a strong input-source user job.',
      priority: 'P0',
      production_wave: 'WAVE_1',
    },
    {
      candidate_id: '10',
      candidate_topic: 'Дизайн карусели онлайн с ИИ',
      primary_query: 'дизайн карусели онлайн с ии',
      user_job: 'Get AI-assisted carousel visual style, template, background, character, CTA, and manual edits.',
      intent_type: 'feature',
      existing_owner: '/ru/ii-generator-karuseley',
      existing_supporting_pages: ['/ru/blog/dizayn-karuseley-neyroset-vs-canva', '/ru/blog/chitabelnost-teksta-v-karuselyah', '/ru/blog/trendovye-shrifty-dlya-karuseley'],
      overlap_routes: ['/ru/generator-karuselej-instagram', '/ru/templates/instagram-carousel'],
      cannibalization_risk: 'medium',
      product_capability: 'confirmed',
      decision: 'STRENGTHEN_EXISTING_OWNER',
      target_route: '/ru/ii-generator-karuseley',
      page_variant: 'commercial_tool',
      unique_angle: 'AI visual controls as a section inside the AI carousel generator owner.',
      boundary: 'No separate design route until the AI generator page clearly owns the visual workflow.',
      internal_links_in: ['/ru/blog/dizayn-karuseley-neyroset-vs-canva', '/ru/blog/chitabelnost-teksta-v-karuselyah'],
      internal_links_out: ['/ru/templates/instagram-carousel', '/ru/blog/trendovye-shrifty-dlya-karuseley'],
      supporting_article_needed: 'no',
      reason: 'Design query overlaps the AI generator and template-selection pages; strengthen the existing owner first.',
      priority: 'P1',
      production_wave: 'WAVE_2',
    },
    {
      candidate_id: '11',
      candidate_topic: 'Примеры каруселей Instagram',
      primary_query: 'примеры каруселей instagram',
      user_job: 'See reusable Instagram carousel examples and move from inspiration to creation.',
      intent_type: 'use-case',
      existing_owner: '/ru/blog/primery-karuseley-instagram',
      existing_supporting_pages: ['/ru/blog/primery-karuseley-instagram', '/ru/blog/best-instagram-carousel-examples', '/ru/templates/instagram-carousel'],
      overlap_routes: ['/ru/examples/instagram-carousel', '/ru/templates/instagram-carousel'],
      cannibalization_risk: 'medium',
      product_capability: 'confirmed',
      decision: 'SUPPORT_WITH_EXISTING_ARTICLES',
      target_route: '/ru/examples/instagram-carousel',
      page_variant: 'example_page',
      unique_angle: 'Commercial examples/gallery page using GoToFlow-style outcomes, with articles retaining broader inspiration.',
      boundary: 'Do not duplicate article listicle copy or template-selection intent.',
      internal_links_in: ['/ru/blog/primery-karuseley-instagram', '/ru/templates/instagram-carousel'],
      internal_links_out: ['/ru/generator-karuselej-instagram', '/ru/blog/primery-karuseley-instagram'],
      supporting_article_needed: 'no',
      reason: 'Good future page, but Wave 1 should avoid a third/fourth variant and use existing examples content as support.',
      priority: 'P1',
      production_wave: 'WAVE_2',
    },
    {
      candidate_id: '12',
      candidate_topic: 'Промпты для каруселей Instagram',
      primary_query: 'промпты для каруселей instagram',
      user_job: 'Find prompt patterns for Instagram carousel structure, text, hook, and CTA.',
      intent_type: 'feature',
      existing_owner: '/ru/blog/prompty-dlya-karuseley-v-instagram',
      existing_supporting_pages: ['/ru/blog/prompty-dlya-karuseley-v-instagram', '/ru/blog/instagram-carousel-prompts'],
      overlap_routes: ['/ru/prompts/instagram-carousel', '/ru/ii-generator-karuseley'],
      cannibalization_risk: 'medium',
      product_capability: 'confirmed',
      decision: 'SUPPORT_WITH_EXISTING_ARTICLES',
      target_route: '/ru/prompts/instagram-carousel',
      page_variant: 'prompt_page',
      unique_angle: 'Prompt library page that converts prompt use into GoToFlow creation.',
      boundary: 'Article remains the educational prompt guide; AI generator owns no-prompt creation.',
      internal_links_in: ['/ru/blog/prompty-dlya-karuseley-v-instagram', '/ru/blog/instagram-carousel-prompts'],
      internal_links_out: ['/ru/ii-generator-karuseley', '/ru/generator-karuselej-instagram'],
      supporting_article_needed: 'no',
      reason: 'Strong support content exists; defer to avoid expanding Wave 1 beyond two variants.',
      priority: 'P1',
      production_wave: 'WAVE_2',
    },
    {
      candidate_id: '13',
      candidate_topic: 'Генератор каруселей LinkedIn',
      primary_query: 'генератор каруселей linkedin',
      user_job: 'Create a LinkedIn carousel or PDF-style expert post from an idea, article, PDF, or video.',
      intent_type: 'tool',
      existing_owner: '/ru/generator-karuselej-linkedin',
      existing_supporting_pages: ['/ru/blog/kak-sdelat-karusel-linkedin-s-ai', '/ru/blog/idei-karuselej-linkedin', '/ru/blog/primery-karuseley-linkedin'],
      overlap_routes: ['/ru/linkedin-carousel-generator', '/ru/ii-generator-karuseley', '/ru/ii-generator-postov-dlya-linkedin'],
      cannibalization_risk: 'medium',
      product_capability: 'confirmed',
      decision: 'STRENGTHEN_EXISTING_OWNER',
      target_route: '/ru/generator-karuselej-linkedin',
      page_variant: 'commercial_tool',
      unique_angle: 'LinkedIn-specific carousel owner with B2B/PDF/document-post context.',
      boundary: 'Do not own generic AI carousel or LinkedIn post text generation.',
      internal_links_in: ['/ru/blog/kak-sdelat-karusel-linkedin-s-ai', '/ru/blog/idei-karuselej-linkedin', '/ru/generator-kontenta'],
      internal_links_out: ['/ru/blog/primery-karuseley-linkedin', '/ru/blog/linkedin-carousel-size-and-specs', '/ru/ii-generator-postov-dlya-linkedin'],
      supporting_article_needed: 'no',
      reason: 'Protected hard-coded route is the correct owner; strengthen instead of creating `/ru/linkedin-carousel-generator`.',
      priority: 'P0',
      production_wave: 'WAVE_1',
    },
    {
      candidate_id: '14',
      candidate_topic: 'Генератор постов для социальных сетей',
      primary_query: 'генератор постов для социальных сетей',
      user_job: 'Create post ideas, structure, text, carousel cards, and CTA for several social platforms.',
      intent_type: 'tool',
      existing_owner: '/ru/generator-kontenta',
      existing_supporting_pages: ['/ru/blog/ii-post-dlya-socsetej', '/ru/blog/neyroset-dlya-postov', '/ru/blog/social-media-post-ideas-for-business'],
      overlap_routes: ['/ru/generator-postov-instagram', '/ru/generator-postov-dlya-socsetey', '/ru/vk-post-generator', '/ru/telegram-post-generator'],
      cannibalization_risk: 'high',
      product_capability: 'confirmed',
      decision: 'STRENGTHEN_EXISTING_OWNER',
      target_route: '/ru/generator-kontenta',
      page_variant: 'commercial_tool',
      unique_angle: 'Broad multi-platform content generator owner.',
      boundary: 'Platform-specific Instagram, VK, Telegram, and LinkedIn jobs should link out and not be swallowed by the broad page.',
      internal_links_in: ['/ru/blog/ii-post-dlya-socsetej', '/ru/blog/neyroset-dlya-postov', '/ru/blog/social-media-post-ideas-for-business'],
      internal_links_out: ['/ru/generator-postov-instagram', '/ru/vk-post-generator', '/ru/telegram-post-generator'],
      supporting_article_needed: 'no',
      reason: 'Existing protected content-generator route should be strengthened; duplicate generic post-generator route would cannibalize it.',
      priority: 'P0',
      production_wave: 'WAVE_1',
    },
    {
      candidate_id: '15',
      candidate_topic: 'ИИ-генератор постов для Instagram',
      primary_query: 'ии генератор постов instagram',
      user_job: 'Generate Instagram post package: idea, caption, carousel/card structure, visual logic, and CTA.',
      intent_type: 'tool',
      existing_owner: '/ru/generator-postov-instagram',
      existing_supporting_pages: ['/ru/blog/kak-sdelat-post-v-instagram-s-ii', '/ru/blog/kakie-posty-delat-v-instagram-idei', '/ru/blog/tekst-i-foto-dlya-posta-instagram'],
      overlap_routes: ['/ru/ii-generator-postov-dlya-instagram', '/ru/generator-kontenta', '/ru/instagram-post-generator'],
      cannibalization_risk: 'medium',
      product_capability: 'confirmed',
      decision: 'STRENGTHEN_EXISTING_OWNER',
      target_route: '/ru/generator-postov-instagram',
      page_variant: 'commercial_tool',
      unique_angle: 'Instagram post package owner, including captions and carousel/cards.',
      boundary: 'Do not replace the carousel generator route or generic content generator.',
      internal_links_in: ['/ru/blog/kak-sdelat-post-v-instagram-s-ii', '/ru/blog/kakie-posty-delat-v-instagram-idei'],
      internal_links_out: ['/ru/generator-karuselej-instagram', '/ru/generator-kontenta', '/ru/blog/instagram-post-size-guide'],
      supporting_article_needed: 'no',
      reason: 'Protected Instagram post generator route already owns this commercial tool intent.',
      priority: 'P0',
      production_wave: 'WAVE_1',
    },
    {
      candidate_id: '16',
      candidate_topic: 'Создание постов для Instagram',
      primary_query: 'создание постов instagram',
      user_job: 'Create a complete Instagram post, not only a caption or hashtag set.',
      intent_type: 'commercial',
      existing_owner: '/ru/generator-postov-instagram',
      existing_supporting_pages: ['/ru/blog/kak-sdelat-post-v-instagram-s-ii', '/ru/blog/foto-dlya-posta-instagram-vizual-s-ii'],
      overlap_routes: ['/ru/generator-postov-instagram', '/ru/generator-kontenta'],
      cannibalization_risk: 'high',
      product_capability: 'confirmed',
      decision: 'MERGE_WITH_EXISTING_PAGE',
      target_route: '/ru/generator-postov-instagram',
      page_variant: 'commercial_tool',
      unique_angle: 'Section inside Instagram post generator for post creation workflow.',
      boundary: 'No standalone `/ru/sozdanie-postov-instagram` route.',
      internal_links_in: ['/ru/blog/kak-sdelat-post-v-instagram-s-ii'],
      internal_links_out: ['/ru/generator-postov-instagram', '/ru/generator-kontenta'],
      supporting_article_needed: 'no',
      reason: 'Near-duplicate of candidate 15 and existing product route.',
      priority: 'P1',
      production_wave: 'WAVE_2',
    },
    {
      candidate_id: '17',
      candidate_topic: 'Создание постов для VK',
      primary_query: 'создание постов для вк',
      user_job: 'Create a VK post for a group or community with structure, text, cards, and CTA.',
      intent_type: 'platform',
      existing_owner: '/ru/vk-post-generator',
      existing_supporting_pages: ['/ru/blog/kak-napisat-post-v-vk-s-pomoshyu-ii', '/ru/blog/temy-postov-dlya-gruppy-vkontakte', '/ru/blog/krasivye-posty-dlya-vk-oformlenie'],
      overlap_routes: ['/ru/generator-kontenta', '/ru/vk-post-generator'],
      cannibalization_risk: 'medium',
      product_capability: 'confirmed',
      decision: 'MERGE_WITH_EXISTING_PAGE',
      target_route: '/ru/vk-post-generator',
      page_variant: 'commercial_tool',
      unique_angle: 'Creation workflow section inside the VK post generator page.',
      boundary: 'Do not split create-VK-post and VK-generator into separate competing pages.',
      internal_links_in: ['/ru/blog/kak-napisat-post-v-vk-s-pomoshyu-ii', '/ru/blog/temy-postov-dlya-gruppy-vkontakte'],
      internal_links_out: ['/ru/generator-kontenta', '/ru/blog/razmer-foto-dlya-posta-vk-formaty'],
      supporting_article_needed: 'no',
      reason: 'The route should be one VK platform owner; creation wording is a section, not a route.',
      priority: 'P1',
      production_wave: 'WAVE_2',
    },
    {
      candidate_id: '18',
      candidate_topic: 'Генератор постов для VK',
      primary_query: 'генератор постов для вк',
      user_job: 'Generate VK group/community posts, rubrics, text blocks, visual cards, and CTA.',
      intent_type: 'platform',
      existing_owner: '/ru/vk-post-generator',
      existing_supporting_pages: ['/ru/blog/kak-napisat-post-v-vk-s-pomoshyu-ii', '/ru/blog/temy-postov-dlya-gruppy-vkontakte', '/ru/blog/razmer-foto-dlya-posta-vk-formaty'],
      overlap_routes: ['/ru/generator-kontenta'],
      cannibalization_risk: 'low',
      product_capability: 'confirmed',
      decision: 'STRENGTHEN_EXISTING_OWNER',
      target_route: '/ru/vk-post-generator',
      page_variant: 'commercial_tool',
      unique_angle: 'VK-specific post generator owner for community and group content.',
      boundary: 'Do not claim direct VK publishing; broad content generation stays with `/ru/generator-kontenta`.',
      internal_links_in: ['/ru/blog/kak-napisat-post-v-vk-s-pomoshyu-ii', '/ru/blog/temy-postov-dlya-gruppy-vkontakte'],
      internal_links_out: ['/ru/generator-kontenta', '/ru/blog/razmer-foto-dlya-posta-vk-formaty', '/ru/blog/krasivye-posty-dlya-vk-oformlenie'],
      supporting_article_needed: 'no',
      reason: 'Existing SEO registry candidate has no protected route collision and should be upgraded through the lifecycle.',
      priority: 'P0',
      production_wave: 'WAVE_1',
    },
    {
      candidate_id: '19',
      candidate_topic: 'Создание постов для Telegram',
      primary_query: 'генератор постов telegram',
      user_job: 'Generate Telegram channel posts, long/short formats, announcements, digests, and CTA.',
      intent_type: 'platform',
      existing_owner: '/ru/telegram-post-generator',
      existing_supporting_pages: ['/ru/blog/kak-vesti-telegram-kanal-biznesu', '/ru/blog/struktura-prodayuschego-posta-v-telegram'],
      overlap_routes: ['/ru/generator-kontenta'],
      cannibalization_risk: 'low',
      product_capability: 'confirmed',
      decision: 'STRENGTHEN_EXISTING_OWNER',
      target_route: '/ru/telegram-post-generator',
      page_variant: 'commercial_tool',
      unique_angle: 'Telegram-specific post generator owner for channels and business content.',
      boundary: 'Do not claim Telegram publishing, bot automation, or guaranteed channel growth.',
      internal_links_in: ['/ru/blog/kak-vesti-telegram-kanal-biznesu', '/ru/blog/struktura-prodayuschego-posta-v-telegram'],
      internal_links_out: ['/ru/generator-kontenta', '/ru/blog/kak-napisat-ekspertnyj-post'],
      supporting_article_needed: 'no',
      reason: 'Existing SEO registry candidate has no protected route collision and platform-specific support content exists.',
      priority: 'P0',
      production_wave: 'WAVE_1',
    },
    {
      candidate_id: '20',
      candidate_topic: 'Карусели для экспертов и экспертных блогов',
      primary_query: 'карусели для экспертов',
      user_job: 'Create expert-blog carousels for education, authority, personal brand, and service selling.',
      intent_type: 'use-case',
      existing_owner: '/ru/blog/karuseli-dlya-ekspertov-s-ii',
      existing_supporting_pages: ['/ru/blog/karuseli-dlya-ekspertov-s-ii', '/ru/blog/karusel-dlya-lichnogo-brenda-s-ii', '/ru/blog/kak-napisat-ekspertnyj-post'],
      overlap_routes: ['/ru/ii-generator-karuseley', '/ru/use-cases/karuseli-dlya-ekspertov'],
      cannibalization_risk: 'low',
      product_capability: 'confirmed',
      decision: 'SUPPORT_WITH_EXISTING_ARTICLES',
      target_route: '/ru/use-cases/karuseli-dlya-ekspertov',
      page_variant: 'use_case_page',
      unique_angle: 'Commercial use-case page for expert-blog carousel outcomes.',
      boundary: 'Article keeps editorial advice and examples; route should focus on GoToFlow creation workflow.',
      internal_links_in: ['/ru/blog/karuseli-dlya-ekspertov-s-ii', '/ru/blog/karusel-dlya-lichnogo-brenda-s-ii'],
      internal_links_out: ['/ru/ii-generator-karuseley', '/ru/blog/kak-napisat-ekspertnyj-post'],
      supporting_article_needed: 'no',
      reason: 'Strong future use-case page, but lower commercial priority than source-input and platform pages in Wave 1.',
      priority: 'P1',
      production_wave: 'WAVE_2',
    },
  ],

  wave1: {
    totalTasks: 10,
    newRoutesCount: 3,
    existingRoutesToStrengthenCount: 7,
    pageVariantsLimit: 2,
    variantsUsed: [
      {
        variant: 'commercial_tool',
        pages: [
          '/ru/generator-karuselej-instagram',
          '/ru/ii-generator-karuseley',
          '/ru/generator-karuselej-linkedin',
          '/ru/generator-kontenta',
          '/ru/generator-postov-instagram',
          '/ru/vk-post-generator',
          '/ru/telegram-post-generator',
        ],
      },
      {
        variant: 'use_case_page',
        pages: [
          '/ru/use-cases/besshovnaya-karusel-instagram',
          '/ru/use-cases/tekst-v-karusel',
          '/ru/use-cases/video-v-karusel',
        ],
      },
    ],
    taskOrder: [
      '01',
      '04',
      '06',
      '07',
      '09',
      '13',
      '14',
      '15',
      '18',
      '19',
    ],
  },

  wave2OrHold: {
    wave2CandidateIds: ['02', '03', '05', '10', '11', '12', '16', '17', '20'],
    holdCandidateIds: ['08'],
    reason: 'Wave 2 keeps comparison, examples, prompts, secondary synonyms, and expert-blog use cases out of the first batch to keep Wave 1 to two variants and avoid duplicate routes.',
  },

  productionBriefsWave1: [
    {
      candidate_id: '01',
      route: '/ru/generator-karuselej-instagram',
      action: 'strengthen_existing_owner',
      lifecycleInitialState: 'planning_only',
      pageType: 'tool',
      pageVariant: 'commercial_tool',
      primaryQuery: 'генератор каруселей для instagram',
      supportingQueries: ['создать карусель instagram', 'карусель инстаграм генератор', 'instagram carousel generator'],
      searchIntent: 'Find a tool to create an Instagram carousel quickly.',
      userJob: 'Create a ready Instagram carousel with structure, slide text, visual style, and CTA.',
      intentOwner: '/ru/generator-karuselej-instagram',
      uniqueAngle: 'Instagram-specific creation route, not a generic carousel or template page.',
      cannibalizationBoundary: 'Do not own template discovery, prompts, examples, LinkedIn, or generic AI carousel intent.',
      competingRoutes: ['/ru/ai-generator-karuselej', '/ru/ii-generator-karuseley', '/ru/templates/instagram-carousel', '/ru/instagram-carousel-generator'],
      pagePromise: 'GoToFlow creates a ready Instagram carousel from an input source and lets the user review/edit before publication.',
      titleDirection: 'Генератор каруселей для Instagram | GoToFlow',
      h1Direction: 'Генератор каруселей для Instagram',
      metaDescriptionDirection: 'Mention AI/templates, 5-10 slide workflow, supported inputs, editing, and no direct publishing claim.',
      heroResult: 'Show finished 4:5 Instagram carousel preview plus source-to-result workflow.',
      quickAnswerPurpose: 'State that GoToFlow creates complete editable carousels, while Instagram supports up to 20 media and GoToFlow creates up to 10 slides.',
      requiredSections: ['hero', 'problem', 'whatItCreates', 'useCases', 'workflow', 'examples', 'benefits', 'faq', 'related', 'finalCta'],
      optionalSections: ['format guidance because Instagram-specific sizes matter'],
      ProductTruthClaims: ['AI, template, seamless, and animated carousel types are available', 'topic/text/link/video/PDF/voice inputs', 'up to 10 GoToFlow slides', '4:5, 1:1, 9:16 formats', 'manual editing and text regeneration'],
      forbiddenClaims: ['direct Instagram publishing', 'guaranteed reach/saves/followers', 'more than 10 GoToFlow slides', 'unsupported photo-only source claim'],
      ctaAction: 'create_carousel',
      ctaDestination: 'https://app.gotoflow.io',
      requiredVisualsMockups: ['source input panel', 'visual route controls', 'ready Instagram carousel result'],
      FAQScope: ['slide limits', 'Instagram media limit', 'editing', 'formats', 'difference from templates and prompts'],
      supportingArticles: ['/ru/blog/kak-sdelat-karusel-dlya-instagram-s-ii', '/ru/blog/karusel-dlya-instagram', '/ru/blog/razmer-karuseli-v-instagram'],
      incomingInternalLinks: ['/ru/templates/instagram-carousel', '/ru/blog/kak-sdelat-karusel-dlya-instagram-s-ii', '/ru/blog/karusel-dlya-instagram'],
      outgoingInternalLinks: ['/ru/templates/instagram-carousel', '/ru/blog/razmer-karuseli-v-instagram', '/ru/blog/prompty-dlya-karuseley-v-instagram'],
      schemaTypes: ['WebPage', 'WebApplication', 'SoftwareApplication', 'Product'],
      indexationPrerequisites: ['route owner approval for existing protected page update', 'content readiness', 'product truth pass', 'rendered review', 'release gate', 'manual indexation approval'],
      productionRisks: ['protected route must not be replaced by registry route', 'must avoid duplicating `/ru/ii-generator-karuseley` copy'],
      acceptanceCriteria: ['Intent owner remains `/ru/generator-karuselej-instagram`', 'No new competing route', 'Related links point to template/prompts/examples as supporting content', 'No sitemap change until release approval'],
    },
    {
      candidate_id: '04',
      route: '/ru/ii-generator-karuseley',
      action: 'strengthen_existing_owner',
      lifecycleInitialState: 'planning_only',
      pageType: 'commercial',
      pageVariant: 'commercial_tool',
      primaryQuery: 'ии генератор каруселей',
      supportingQueries: ['нейросеть для каруселей', 'создать карусель с ии', 'ai генератор каруселей'],
      searchIntent: 'Find an AI tool for creating carousels from multiple input sources.',
      userJob: 'Use AI to turn a topic, text, link, video, PDF, or voice input into an editable carousel.',
      intentOwner: '/ru/ii-generator-karuseley',
      uniqueAngle: 'AI-first source-to-ready-carousel route.',
      cannibalizationBoundary: 'Do not own Instagram-only, LinkedIn-only, prompt-library, or comparison intent.',
      competingRoutes: ['/ru/ai-generator-karuselej', '/ru/generator-karuselej-instagram', '/ru/generator-karuseley'],
      pagePromise: 'Create an editable AI carousel quickly while keeping author review and manual control.',
      titleDirection: 'ИИ-генератор каруселей | GoToFlow',
      h1Direction: 'ИИ-генератор каруселей',
      metaDescriptionDirection: 'Mention inputs, AI/template/seamless/animated options, editing, and 60-second creation.',
      heroResult: 'Show multi-input source choices and ready carousel result.',
      quickAnswerPurpose: 'Explain what the AI generator creates and which sources are supported.',
      requiredSections: ['hero', 'problem', 'whatItCreates', 'useCases', 'workflow', 'examples', 'benefits', 'faq', 'related', 'finalCta'],
      optionalSections: ['input source selector because this is the core differentiator'],
      ProductTruthClaims: ['topic, text, link, video, PDF, and voice inputs', 'ready in 60 seconds', 'text editing and regeneration', 'AI style/custom prompt/template/background/character/CTA'],
      forbiddenClaims: ['full automation without review', 'automatic social publishing', 'guaranteed performance'],
      ctaAction: 'create_ai_carousel',
      ctaDestination: 'https://app.gotoflow.io',
      requiredVisualsMockups: ['input-source grid', 'text review/regeneration mockup', 'visual settings mockup', 'ready carousel'],
      FAQScope: ['supported inputs', 'editing', 'formats', 'slide count', 'difference from ChatGPT and templates'],
      supportingArticles: ['/ru/blog/ii-dlya-karuseley', '/ru/blog/tekst-v-karusel-neyroset', '/ru/blog/luchshie-ai-generatory-karuselej'],
      incomingInternalLinks: ['/ru/blog/ii-dlya-karuseley', '/ru/blog/tekst-v-karusel-neyroset', '/ru/blog/luchshie-ai-generatory-karuselej'],
      outgoingInternalLinks: ['/ru/generator-karuselej-instagram', '/ru/generator-karuselej-linkedin', '/ru/blog/prompty-dlya-karuseley-v-instagram'],
      schemaTypes: ['WebPage', 'WebApplication', 'SoftwareApplication', 'Product'],
      indexationPrerequisites: ['protected route owner update approval', 'rendered review', 'content uniqueness review', 'release gate'],
      productionRisks: ['route migration is not approved for registry ownership', 'copy can become too generic and cannibalize platform pages'],
      acceptanceCriteria: ['AI carousel owner stays protected', 'Input-source claims match Product Truth', 'No direct publishing claim'],
    },
    {
      candidate_id: '06',
      route: '/ru/use-cases/besshovnaya-karusel-instagram',
      action: 'create_new_planning_route',
      lifecycleInitialState: 'planning_only',
      pageType: 'useCase',
      pageVariant: 'use_case_page',
      primaryQuery: 'создать бесшовную карусель instagram',
      supportingQueries: ['бесшовная карусель в инстаграм', 'seamless carousel instagram', 'бесшовная карусель онлайн'],
      searchIntent: 'Create a seamless Instagram carousel with product help.',
      userJob: 'Create seamless carousel output without treating manual panorama slicing as the main product promise.',
      intentOwner: '/ru/use-cases/besshovnaya-karusel-instagram',
      uniqueAngle: 'Commercial feature workflow for seamless carousel creation in GoToFlow.',
      cannibalizationBoundary: 'Technical slicing math and tool comparison stay in `/ru/blog/besshovnaya-karusel-v-instagram`.',
      competingRoutes: ['/ru/generator-karuselej-instagram', '/ru/templates/instagram-carousel', '/ru/blog/besshovnaya-karusel-v-instagram'],
      pagePromise: 'Start from an idea/source, choose seamless carousel type, review text and visual flow, then edit the result.',
      titleDirection: 'Создать бесшовную карусель Instagram | GoToFlow',
      h1Direction: 'Создать бесшовную карусель Instagram',
      metaDescriptionDirection: 'Mention seamless carousel type, editable result, 5-10 slides, and supporting guide for manual slicing.',
      heroResult: 'Show continuous-slide carousel preview with a visible seam-safe flow.',
      quickAnswerPurpose: 'Define seamless carousel in product terms and link technical details to the article.',
      requiredSections: ['hero', 'scenario', 'workflow', 'examples', 'benefits', 'faq', 'related', 'finalCta'],
      optionalSections: ['technical caveat block to separate product workflow from manual slicing'],
      ProductTruthClaims: ['seamless carousel available', 'manual editing', '4:5, 1:1, 9:16 formats', 'up to 10 slides'],
      forbiddenClaims: ['automatic perfect panorama slicing from uploaded photo', 'direct Instagram publishing', 'guaranteed engagement'],
      ctaAction: 'create_seamless_carousel',
      ctaDestination: 'https://app.gotoflow.io',
      requiredVisualsMockups: ['seamless carousel type selection', 'continuous visual preview', 'editor result'],
      FAQScope: ['what seamless means', 'slide count', 'manual review at seams', 'difference from normal carousel', 'when to use technical article'],
      supportingArticles: ['/ru/blog/besshovnaya-karusel-v-instagram', '/ru/blog/kak-narezat-foto-dlya-karuseli', '/ru/blog/razmer-karuseli-v-instagram'],
      incomingInternalLinks: ['/ru/blog/besshovnaya-karusel-v-instagram', '/ru/blog/kak-narezat-foto-dlya-karuseli', '/ru/generator-karuselej-instagram'],
      outgoingInternalLinks: ['/ru/generator-karuselej-instagram', '/ru/blog/besshovnaya-karusel-v-instagram', '/ru/blog/razmer-karuseli-v-instagram'],
      schemaTypes: ['WebPage', 'WebApplication', 'SoftwareApplication'],
      indexationPrerequisites: ['new registry entry starts planning_only', 'URL origin proof', 'route review', 'noindex review before indexation', 'visual seam QA'],
      productionRisks: ['overpromising automatic panoramic photo slicing', 'duplicating technical article'],
      acceptanceCriteria: ['Route is not added to sitemap in planning state', 'Feature claim uses seamless carousel Product Truth only', 'Article remains informational owner'],
    },
    {
      candidate_id: '07',
      route: '/ru/use-cases/tekst-v-karusel',
      action: 'create_new_planning_route',
      lifecycleInitialState: 'planning_only',
      pageType: 'useCase',
      pageVariant: 'use_case_page',
      primaryQuery: 'текст в карусель',
      supportingQueries: ['текст в карусель нейросеть', 'создать карусель из текста', 'статья в карусель'],
      searchIntent: 'Turn existing text into a carousel.',
      userJob: 'Paste text or use an existing material and get a structured carousel with editable slide text.',
      intentOwner: '/ru/use-cases/tekst-v-karusel',
      uniqueAngle: 'Commercial input-source page for text-to-carousel conversion.',
      cannibalizationBoundary: 'The article owns step-by-step education; this route owns the product conversion workflow.',
      competingRoutes: ['/ru/ii-generator-karuseley', '/ru/ai-generator-karuselej', '/ru/blog/tekst-v-karusel-neyroset'],
      pagePromise: 'Convert text into a slide structure, concise slide copy, visual style, and CTA.',
      titleDirection: 'Текст в карусель с ИИ | GoToFlow',
      h1Direction: 'Создать карусель из текста',
      metaDescriptionDirection: 'Mention text input, slide structure, editing/regeneration, and ready carousel result.',
      heroResult: 'Before/after from paragraph text to 5-slide carousel.',
      quickAnswerPurpose: 'Explain when to use text-to-carousel and how GoToFlow shortens source material.',
      requiredSections: ['hero', 'scenario', 'workflow', 'examples', 'benefits', 'faq', 'related', 'finalCta'],
      optionalSections: ['source quality checklist because text density affects output quality'],
      ProductTruthClaims: ['text input available', 'slide text output', 'text editing and regeneration', 'ready carousel result'],
      forbiddenClaims: ['fact checking by AI', 'perfect summary without human review', 'direct publishing'],
      ctaAction: 'convert_text_to_carousel',
      ctaDestination: 'https://app.gotoflow.io',
      requiredVisualsMockups: ['text source field', 'slide text review', 'ready carousel preview'],
      FAQScope: ['long text handling', 'how many slides', 'editing', 'article vs post input', 'formats'],
      supportingArticles: ['/ru/blog/tekst-v-karusel-neyroset', '/ru/blog/chitabelnost-teksta-v-karuselyah'],
      incomingInternalLinks: ['/ru/blog/tekst-v-karusel-neyroset', '/ru/ii-generator-karuseley'],
      outgoingInternalLinks: ['/ru/ii-generator-karuseley', '/ru/blog/tekst-v-karusel-neyroset', '/ru/blog/chitabelnost-teksta-v-karuselyah'],
      schemaTypes: ['WebPage', 'WebApplication', 'SoftwareApplication'],
      indexationPrerequisites: ['planning_only registry entry only', 'noindex review page before indexation', 'content readiness and uniqueness review'],
      productionRisks: ['claiming automatic factual compression', 'overlapping AI carousel generator too much'],
      acceptanceCriteria: ['Product page is conversion-focused', 'Existing article remains how-to owner', 'No sitemap entry while planning_only'],
    },
    {
      candidate_id: '09',
      route: '/ru/use-cases/video-v-karusel',
      action: 'create_new_planning_route',
      lifecycleInitialState: 'planning_only',
      pageType: 'useCase',
      pageVariant: 'use_case_page',
      primaryQuery: 'создать карусель из видео',
      supportingQueries: ['видео в карусель', 'reels в карусель', 'youtube в карусель'],
      searchIntent: 'Repurpose video content into carousel slides.',
      userJob: 'Use a video, Reels, webinar, or script as source material for a carousel.',
      intentOwner: '/ru/use-cases/video-v-karusel',
      uniqueAngle: 'Commercial video-input carousel workflow.',
      cannibalizationBoundary: 'The blog article owns repurposing education; this page owns product conversion.',
      competingRoutes: ['/ru/ii-generator-karuseley', '/ru/blog/kak-sdelat-karusel-iz-video-s-ii', '/ru/generator-karuselej-linkedin'],
      pagePromise: 'GoToFlow uses video as a source to extract structure, slide copy, visual flow, and CTA for a carousel.',
      titleDirection: 'Создать карусель из видео | GoToFlow',
      h1Direction: 'Создать карусель из видео',
      metaDescriptionDirection: 'Mention video input, Reels/webinar reuse, editable slide text, and final carousel.',
      heroResult: 'Video source card next to generated carousel slide sequence.',
      quickAnswerPurpose: 'Clarify that video is a supported source and the result still requires review/editing.',
      requiredSections: ['hero', 'scenario', 'workflow', 'examples', 'benefits', 'faq', 'related', 'finalCta'],
      optionalSections: ['repurposing examples because video source types differ'],
      ProductTruthClaims: ['video input available', 'topic/link/text/PDF/voice alternatives', 'text review and regeneration', 'ready carousel result'],
      forbiddenClaims: ['automatic copyright clearance', 'guaranteed transcript accuracy without review', 'direct publishing'],
      ctaAction: 'turn_video_into_carousel',
      ctaDestination: 'https://app.gotoflow.io',
      requiredVisualsMockups: ['video/link input', 'transcript-to-structure step', 'ready carousel preview'],
      FAQScope: ['source types', 'short vs long video', 'editing transcript-derived text', 'LinkedIn vs Instagram output'],
      supportingArticles: ['/ru/blog/kak-sdelat-karusel-iz-video-s-ii', '/ru/blog/kak-peredelat-youtube-v-karusel-linkedin'],
      incomingInternalLinks: ['/ru/blog/kak-sdelat-karusel-iz-video-s-ii', '/ru/ii-generator-karuseley'],
      outgoingInternalLinks: ['/ru/ii-generator-karuseley', '/ru/blog/kak-sdelat-karusel-iz-video-s-ii', '/ru/blog/kak-peredelat-youtube-v-karusel-linkedin'],
      schemaTypes: ['WebPage', 'WebApplication', 'SoftwareApplication'],
      indexationPrerequisites: ['planning_only route record', 'route ownership check', 'content readiness', 'visual source/result QA'],
      productionRisks: ['copyright implication', 'unverified transcript claims', 'overlap with LinkedIn-specific YouTube article'],
      acceptanceCriteria: ['Video support matches Product Truth', 'No copyright or automatic publishing claims', 'Article remains supporting informational owner'],
    },
    {
      candidate_id: '13',
      route: '/ru/generator-karuselej-linkedin',
      action: 'strengthen_existing_owner',
      lifecycleInitialState: 'planning_only',
      pageType: 'tool',
      pageVariant: 'commercial_tool',
      primaryQuery: 'генератор каруселей linkedin',
      supportingQueries: ['linkedin carousel generator', 'карусель linkedin с ии', 'создать linkedin carousel'],
      searchIntent: 'Find a tool to create LinkedIn carousel/document posts.',
      userJob: 'Turn an expert idea, article, PDF, or video into a professional LinkedIn carousel.',
      intentOwner: '/ru/generator-karuselej-linkedin',
      uniqueAngle: 'LinkedIn/B2B carousel creation with professional tone and PDF/document context.',
      cannibalizationBoundary: 'Do not own generic carousel, Instagram carousel, or LinkedIn text-post generator intent.',
      competingRoutes: ['/ru/linkedin-carousel-generator', '/ru/ii-generator-karuseley', '/ru/ii-generator-postov-dlya-linkedin'],
      pagePromise: 'Create a LinkedIn-ready carousel structure and slide text that can be reviewed and adapted for professional publication.',
      titleDirection: 'Генератор каруселей для LinkedIn | GoToFlow',
      h1Direction: 'Генератор каруселей для LinkedIn',
      metaDescriptionDirection: 'Mention B2B/expert content, PDF/document-style carousels, source inputs, and editing.',
      heroResult: 'Professional LinkedIn carousel preview with source input and result.',
      quickAnswerPurpose: 'Explain what a LinkedIn carousel generator does and how it differs from Instagram and text posts.',
      requiredSections: ['hero', 'problem', 'whatItCreates', 'useCases', 'workflow', 'examples', 'benefits', 'faq', 'related', 'finalCta'],
      optionalSections: ['LinkedIn format caveat for PDF/document publishing workflow'],
      ProductTruthClaims: ['PDF input available', 'video/text/link/topic inputs', 'ready carousel', 'manual editing', 'text regeneration'],
      forbiddenClaims: ['automatic LinkedIn publishing', 'guaranteed B2B leads', 'unsupported PDF export specifics unless verified'],
      ctaAction: 'create_linkedin_carousel',
      ctaDestination: 'https://app.gotoflow.io',
      requiredVisualsMockups: ['LinkedIn source input', 'B2B carousel result', 'professional text review'],
      FAQScope: ['LinkedIn vs Instagram', 'PDF/document post context', 'B2B cases', 'editing and fact review'],
      supportingArticles: ['/ru/blog/kak-sdelat-karusel-linkedin-s-ai', '/ru/blog/idei-karuselej-linkedin', '/ru/blog/primery-karuseley-linkedin'],
      incomingInternalLinks: ['/ru/blog/kak-sdelat-karusel-linkedin-s-ai', '/ru/blog/idei-karuselej-linkedin', '/ru/generator-kontenta'],
      outgoingInternalLinks: ['/ru/blog/primery-karuseley-linkedin', '/ru/blog/linkedin-carousel-size-and-specs', '/ru/ii-generator-postov-dlya-linkedin'],
      schemaTypes: ['WebPage', 'WebApplication', 'SoftwareApplication', 'Product'],
      indexationPrerequisites: ['existing protected route owner update approval', 'content readiness', 'rendered review', 'release gate'],
      productionRisks: ['B2B claims must not invent metrics or clients', 'route `/ru/linkedin-carousel-generator` must not compete'],
      acceptanceCriteria: ['Protected route remains owner', 'B2B examples are realistic and non-fake', 'Supporting LinkedIn articles linked'],
    },
    {
      candidate_id: '14',
      route: '/ru/generator-kontenta',
      action: 'strengthen_existing_owner',
      lifecycleInitialState: 'planning_only',
      pageType: 'commercial',
      pageVariant: 'commercial_tool',
      primaryQuery: 'генератор постов для социальных сетей',
      supportingQueries: ['генератор контента для соцсетей', 'создать пост с ии', 'посты для соцсетей'],
      searchIntent: 'Find a broad tool for social media post/content creation.',
      userJob: 'Create ideas, text, structure, visual cards, and CTA for multiple social channels.',
      intentOwner: '/ru/generator-kontenta',
      uniqueAngle: 'Broad content generator owner that routes platform-specific jobs to dedicated pages.',
      cannibalizationBoundary: 'Do not absorb Instagram, VK, Telegram, LinkedIn, or carousel-specific route ownership.',
      competingRoutes: ['/ru/generator-postov-instagram', '/ru/vk-post-generator', '/ru/telegram-post-generator', '/ru/ii-generator-karuseley'],
      pagePromise: 'GoToFlow helps prepare social post content packages from topics and source materials.',
      titleDirection: 'Генератор постов для социальных сетей | GoToFlow',
      h1Direction: 'Генератор постов для социальных сетей',
      metaDescriptionDirection: 'Position as broad content generator with links to platform pages.',
      heroResult: 'Multi-platform content package preview: text, card structure, CTA.',
      quickAnswerPurpose: 'Clarify what the broad generator owns and when to use platform-specific pages.',
      requiredSections: ['hero', 'problem', 'whatItCreates', 'useCases', 'workflow', 'examples', 'benefits', 'faq', 'related', 'finalCta'],
      optionalSections: ['platform chooser because intent boundaries matter'],
      ProductTruthClaims: ['topic/text/link/video/PDF/voice inputs', 'slide text and visual carousel output', 'manual editing', 'CTA settings'],
      forbiddenClaims: ['direct publishing to platforms', 'full channel management automation', 'guaranteed engagement'],
      ctaAction: 'create_social_content',
      ctaDestination: 'https://app.gotoflow.io',
      requiredVisualsMockups: ['platform chooser', 'source input', 'content package result'],
      FAQScope: ['difference from Instagram/VK/Telegram pages', 'supported input sources', 'editing', 'publishing limitations'],
      supportingArticles: ['/ru/blog/ii-post-dlya-socsetej', '/ru/blog/neyroset-dlya-postov', '/ru/blog/social-media-post-ideas-for-business'],
      incomingInternalLinks: ['/ru/blog/ii-post-dlya-socsetej', '/ru/blog/neyroset-dlya-postov', '/ru/blog/social-media-post-ideas-for-business'],
      outgoingInternalLinks: ['/ru/generator-postov-instagram', '/ru/vk-post-generator', '/ru/telegram-post-generator'],
      schemaTypes: ['WebPage', 'WebApplication', 'SoftwareApplication', 'Product'],
      indexationPrerequisites: ['protected route owner update approval', 'intent boundary QA', 'content readiness', 'release gate'],
      productionRisks: ['cannibalizing platform pages', 'overbroad generic copy'],
      acceptanceCriteria: ['Clear platform link-out block', 'No duplicate of Instagram/VK/Telegram briefs', 'No direct publishing claim'],
    },
    {
      candidate_id: '15',
      route: '/ru/generator-postov-instagram',
      action: 'strengthen_existing_owner',
      lifecycleInitialState: 'planning_only',
      pageType: 'tool',
      pageVariant: 'commercial_tool',
      primaryQuery: 'ии генератор постов instagram',
      supportingQueries: ['генератор постов instagram', 'создать пост instagram', 'пост в instagram с ии'],
      searchIntent: 'Find a tool for creating Instagram post packages.',
      userJob: 'Create an Instagram post with idea, caption, carousel/card structure, visual logic, and CTA.',
      intentOwner: '/ru/generator-postov-instagram',
      uniqueAngle: 'Instagram post package owner, not only caption generation.',
      cannibalizationBoundary: 'Do not own Instagram carousel-only route or broad social content route.',
      competingRoutes: ['/ru/ii-generator-postov-dlya-instagram', '/ru/generator-kontenta', '/ru/generator-karuselej-instagram'],
      pagePromise: 'Create Instagram post content with text and visual/card structure, then review/edit before publishing.',
      titleDirection: 'ИИ-генератор постов для Instagram | GoToFlow',
      h1Direction: 'Генератор постов для Instagram',
      metaDescriptionDirection: 'Mention caption, cards/carousel, CTA, editing, and no direct publishing.',
      heroResult: 'Instagram post package preview with cards and caption.',
      quickAnswerPurpose: 'Separate Instagram post package from carousel-only creation and generic content generation.',
      requiredSections: ['hero', 'problem', 'whatItCreates', 'useCases', 'workflow', 'examples', 'benefits', 'faq', 'related', 'finalCta'],
      optionalSections: ['caption-and-visual sync checklist'],
      ProductTruthClaims: ['text and visual carousel output', 'manual editing', 'CTA settings', '4:5/1:1/9:16 formats'],
      forbiddenClaims: ['automatic Instagram posting', 'hashtag performance guarantees', 'fake audience growth'],
      ctaAction: 'create_instagram_post',
      ctaDestination: 'https://app.gotoflow.io',
      requiredVisualsMockups: ['caption plus cards preview', 'Instagram format controls', 'ready post package'],
      FAQScope: ['caption vs carousel', 'editing', 'formats', 'fact/tone review', 'difference from generic generator'],
      supportingArticles: ['/ru/blog/kak-sdelat-post-v-instagram-s-ii', '/ru/blog/kakie-posty-delat-v-instagram-idei', '/ru/blog/tekst-i-foto-dlya-posta-instagram'],
      incomingInternalLinks: ['/ru/blog/kak-sdelat-post-v-instagram-s-ii', '/ru/blog/kakie-posty-delat-v-instagram-idei'],
      outgoingInternalLinks: ['/ru/generator-karuselej-instagram', '/ru/generator-kontenta', '/ru/blog/instagram-post-size-guide'],
      schemaTypes: ['WebPage', 'WebApplication', 'SoftwareApplication', 'Product'],
      indexationPrerequisites: ['protected route owner update approval', 'content readiness', 'route intent check', 'release gate'],
      productionRisks: ['too much overlap with carousel generator', 'caption-only promise would undersell product truth'],
      acceptanceCriteria: ['Instagram post owner remains protected', 'Carousel relation is cross-linked, not duplicated', 'No auto-publish claim'],
    },
    {
      candidate_id: '18',
      route: '/ru/vk-post-generator',
      action: 'strengthen_existing_registry_owner',
      lifecycleInitialState: 'planning_only',
      pageType: 'tool',
      pageVariant: 'commercial_tool',
      primaryQuery: 'генератор постов для вк',
      supportingQueries: ['генератор постов вконтакте', 'пост для группы вк', 'контент для сообщества вк'],
      searchIntent: 'Find a tool for VK group/community post creation.',
      userJob: 'Create VK post text, rubrics, card blocks, and CTA for a group or community.',
      intentOwner: '/ru/vk-post-generator',
      uniqueAngle: 'VK-specific platform owner for groups and communities.',
      cannibalizationBoundary: 'Broad social content stays on `/ru/generator-kontenta`; creation synonym candidate 17 merges here.',
      competingRoutes: ['/ru/generator-kontenta', '/ru/blog/kak-napisat-post-v-vk-s-pomoshyu-ii'],
      pagePromise: 'Prepare VK community post drafts with structure, text blocks, visual card logic, and an engagement CTA.',
      titleDirection: 'Генератор постов для ВК | GoToFlow',
      h1Direction: 'Генератор постов для ВК',
      metaDescriptionDirection: 'Mention VK groups/communities, rubrics, card text, editing, and no direct publishing.',
      heroResult: 'VK group post draft with text blocks and card sequence.',
      quickAnswerPurpose: 'Clarify that GoToFlow prepares content, not automatic VK publishing.',
      requiredSections: ['hero', 'problem', 'whatItCreates', 'useCases', 'workflow', 'examples', 'benefits', 'faq', 'related', 'finalCta'],
      optionalSections: ['VK format guidance because platform behavior differs from Instagram/Telegram'],
      ProductTruthClaims: ['topic/text/link/video/PDF/voice inputs', 'text and visual output', 'manual editing', 'CTA settings'],
      forbiddenClaims: ['automatic VK publishing', 'VK algorithm guarantees', 'unsupported native VK integration'],
      ctaAction: 'create_vk_post',
      ctaDestination: 'https://app.gotoflow.io',
      requiredVisualsMockups: ['VK community use-case card', 'rubric-to-post workflow', 'card/text result'],
      FAQScope: ['VK groups vs personal page', 'cards vs text post', 'editing', 'publishing limitation', 'difference from broad generator'],
      supportingArticles: ['/ru/blog/kak-napisat-post-v-vk-s-pomoshyu-ii', '/ru/blog/temy-postov-dlya-gruppy-vkontakte', '/ru/blog/razmer-foto-dlya-posta-vk-formaty'],
      incomingInternalLinks: ['/ru/blog/kak-napisat-post-v-vk-s-pomoshyu-ii', '/ru/blog/temy-postov-dlya-gruppy-vkontakte'],
      outgoingInternalLinks: ['/ru/generator-kontenta', '/ru/blog/razmer-foto-dlya-posta-vk-formaty', '/ru/blog/krasivye-posty-dlya-vk-oformlenie'],
      schemaTypes: ['WebPage', 'WebApplication', 'SoftwareApplication'],
      indexationPrerequisites: ['registry entry remains planning_only/noindex until route review', 'content readiness', 'related link check', 'release gate'],
      productionRisks: ['current registry candidate exists but should not become sitemap eligible without approval', 'claims may drift into unsupported VK publishing'],
      acceptanceCriteria: ['Candidate 17 merges into this owner', 'No direct publishing claim', 'No sitemap entry until indexable_approved'],
    },
    {
      candidate_id: '19',
      route: '/ru/telegram-post-generator',
      action: 'strengthen_existing_registry_owner',
      lifecycleInitialState: 'planning_only',
      pageType: 'tool',
      pageVariant: 'commercial_tool',
      primaryQuery: 'генератор постов telegram',
      supportingQueries: ['создание постов для telegram', 'пост для телеграм канала', 'генератор постов телеграм'],
      searchIntent: 'Find a tool for Telegram channel post creation.',
      userJob: 'Create Telegram channel posts, long/short formats, announcements, digests, and CTA.',
      intentOwner: '/ru/telegram-post-generator',
      uniqueAngle: 'Telegram-specific platform owner for channels and business content.',
      cannibalizationBoundary: 'Broad social content stays on `/ru/generator-kontenta`; Telegram strategy articles stay informational.',
      competingRoutes: ['/ru/generator-kontenta', '/ru/blog/kak-vesti-telegram-kanal-biznesu', '/ru/blog/struktura-prodayuschego-posta-v-telegram'],
      pagePromise: 'Prepare Telegram post drafts with a clear thought, structure, length option, and CTA for channel publication.',
      titleDirection: 'Генератор постов для Telegram | GoToFlow',
      h1Direction: 'Генератор постов для Telegram',
      metaDescriptionDirection: 'Mention Telegram channel posts, short/long formats, editing, and no bot/publishing claim.',
      heroResult: 'Telegram channel post draft with short/long toggle and CTA.',
      quickAnswerPurpose: 'Clarify that GoToFlow creates editable content drafts for Telegram, not automated channel management.',
      requiredSections: ['hero', 'problem', 'whatItCreates', 'useCases', 'workflow', 'examples', 'benefits', 'faq', 'related', 'finalCta'],
      optionalSections: ['short-vs-long format guide because Telegram reading behavior matters'],
      ProductTruthClaims: ['topic/text/link/video/PDF/voice inputs', 'manual editing', 'text regeneration', 'CTA settings'],
      forbiddenClaims: ['automatic Telegram posting', 'bot management', 'guaranteed channel growth', 'Telegram Ads claims'],
      ctaAction: 'create_telegram_post',
      ctaDestination: 'https://app.gotoflow.io',
      requiredVisualsMockups: ['Telegram channel input context', 'short/long post result', 'CTA review'],
      FAQScope: ['short vs long posts', 'channel voice', 'editing', 'publishing limitation', 'difference from broad generator'],
      supportingArticles: ['/ru/blog/kak-vesti-telegram-kanal-biznesu', '/ru/blog/struktura-prodayuschego-posta-v-telegram', '/ru/blog/kak-napisat-ekspertnyj-post'],
      incomingInternalLinks: ['/ru/blog/kak-vesti-telegram-kanal-biznesu', '/ru/blog/struktura-prodayuschego-posta-v-telegram'],
      outgoingInternalLinks: ['/ru/generator-kontenta', '/ru/blog/kak-napisat-ekspertnyj-post'],
      schemaTypes: ['WebPage', 'WebApplication', 'SoftwareApplication'],
      indexationPrerequisites: ['registry entry remains planning_only/noindex until route review', 'content readiness', 'product truth pass', 'release gate'],
      productionRisks: ['copy can imply unsupported Telegram automation', 'strategy article cannibalization if page becomes too educational'],
      acceptanceCriteria: ['Page is product workflow focused', 'Telegram articles remain supporting guides', 'No sitemap entry until indexable_approved'],
    },
  ],

  articlesPolicy: {
    reusedExistingArticles: [
      { article: '/ru/blog/kak-sdelat-karusel-dlya-instagram-s-ii', supports: ['01', '02'] },
      { article: '/ru/blog/karusel-dlya-instagram', supports: ['01', '02'] },
      { article: '/ru/blog/razmer-karuseli-v-instagram', supports: ['01', '06'] },
      { article: '/ru/blog/ii-dlya-karuseley', supports: ['04'] },
      { article: '/ru/blog/tekst-v-karusel-neyroset', supports: ['04', '07'] },
      { article: '/ru/blog/luchshie-ai-generatory-karuselej', supports: ['03', '04', '05'] },
      { article: '/ru/blog/besshovnaya-karusel-v-instagram', supports: ['06'] },
      { article: '/ru/blog/kak-narezat-foto-dlya-karuseli', supports: ['06', '08'] },
      { article: '/ru/blog/kak-sdelat-karusel-iz-video-s-ii', supports: ['09'] },
      { article: '/ru/blog/dizayn-karuseley-neyroset-vs-canva', supports: ['05', '10'] },
      { article: '/ru/blog/primery-karuseley-instagram', supports: ['11'] },
      { article: '/ru/blog/prompty-dlya-karuseley-v-instagram', supports: ['12'] },
      { article: '/ru/blog/kak-sdelat-karusel-linkedin-s-ai', supports: ['13'] },
      { article: '/ru/blog/idei-karuselej-linkedin', supports: ['13'] },
      { article: '/ru/blog/ii-post-dlya-socsetej', supports: ['14'] },
      { article: '/ru/blog/kak-sdelat-post-v-instagram-s-ii', supports: ['15', '16'] },
      { article: '/ru/blog/kak-napisat-post-v-vk-s-pomoshyu-ii', supports: ['17', '18'] },
      { article: '/ru/blog/temy-postov-dlya-gruppy-vkontakte', supports: ['17', '18'] },
      { article: '/ru/blog/kak-vesti-telegram-kanal-biznesu', supports: ['19'] },
      { article: '/ru/blog/struktura-prodayuschego-posta-v-telegram', supports: ['19'] },
      { article: '/ru/blog/karuseli-dlya-ekspertov-s-ii', supports: ['20'] },
    ],
    articleGaps: [
      {
        topic: 'photo-input product workflow',
        status: 'blocked_by_product_truth',
        reason: 'There is enough technical article coverage for photo slicing, but no confirmed product workflow for photo as first-class input.',
      },
    ],
    newArticlesRequired: [],
    totalNewArticlesRequired: 0,
  },

  cannibalizationRules: [
    {
      cluster: 'Instagram carousel generator',
      mainOwner: '/ru/generator-karuselej-instagram',
      supportingOwner: '/ru/templates/instagram-carousel',
      forbiddenCompetingRoutes: ['/ru/instagram-carousel-generator', '/ru/sozdat-karusel-instagram', '/ru/dizayn-karuseli-instagram'],
      internalLinkDirection: 'Articles/templates/prompts/examples link into `/ru/generator-karuselej-instagram`; generator links out to articles for detail.',
    },
    {
      cluster: 'AI carousel generator',
      mainOwner: '/ru/ii-generator-karuseley',
      supportingOwner: '/ru/blog/ii-dlya-karuseley',
      forbiddenCompetingRoutes: ['/ru/generator-karuseley-onlayn', '/ru/ii-dizayn-karuseley'],
      internalLinkDirection: 'Input-source use-case pages link to `/ru/ii-generator-karuseley`; AI route links out by platform/use case.',
    },
    {
      cluster: 'Social post generator',
      mainOwner: '/ru/generator-kontenta',
      supportingOwner: '/ru/blog/ii-post-dlya-socsetej',
      forbiddenCompetingRoutes: ['/ru/generator-postov-dlya-socsetey'],
      internalLinkDirection: 'Broad social articles link to `/ru/generator-kontenta`; broad route links to platform pages.',
    },
    {
      cluster: 'Instagram posts',
      mainOwner: '/ru/generator-postov-instagram',
      supportingOwner: '/ru/blog/kak-sdelat-post-v-instagram-s-ii',
      forbiddenCompetingRoutes: ['/ru/sozdanie-postov-instagram', '/ru/instagram-post-generator'],
      internalLinkDirection: 'Instagram post articles link to Instagram post generator; carousel route remains separate.',
    },
    {
      cluster: 'VK posts',
      mainOwner: '/ru/vk-post-generator',
      supportingOwner: '/ru/blog/kak-napisat-post-v-vk-s-pomoshyu-ii',
      forbiddenCompetingRoutes: ['/ru/sozdanie-postov-vk', '/ru/generator-postov-vkontakte'],
      internalLinkDirection: 'VK guides link to VK generator; broad generator links to VK when user chooses platform.',
    },
    {
      cluster: 'Telegram posts',
      mainOwner: '/ru/telegram-post-generator',
      supportingOwner: '/ru/blog/kak-vesti-telegram-kanal-biznesu',
      forbiddenCompetingRoutes: ['/ru/sozdanie-postov-telegram', '/ru/generator-postov-telegram-kanal'],
      internalLinkDirection: 'Telegram strategy/how-to articles link to Telegram generator; generator links out for strategy detail.',
    },
  ],

  batchProductionPlan: {
    standardWaveSize: 10,
    maximumDailyTarget: 20,
    pageVariantsLimitPerWave: 3,
    wave1Variants: ['commercial_tool', 'use_case_page'],
    sharedComponents: [
      'SeoPageTemplate',
      'SeoPageHero',
      'SeoProductWorkflowShowcase',
      'SeoPageWorkflow',
      'SeoPageExamples',
      'SeoPageFAQ',
      'SeoPageRelatedLinks',
      'SeoPageCTA',
    ],
    reusableBlocks: [
      'source input workflow',
      'text review/regeneration',
      'visual route settings',
      'ready carousel or post result',
      'platform boundary FAQ',
      'Product Truth CTA',
    ],
    uniqueDataPerPage: [
      'primary query',
      'user job',
      'route owner',
      'platform/source-specific examples',
      'FAQ scope',
      'supporting article links',
      'cannibalization boundary',
    ],
    requiredVisuals: [
      'one source-to-result mockup pattern per variant',
      'platform-specific result previews for Instagram, LinkedIn, VK, Telegram',
      'seamless/text/video use-case previews for source-input pages',
    ],
    batchChecks: [
      'npm run check:seo',
      'route intent ownership',
      'Product Truth claims',
      'content readiness for noindex/indexable states',
      'related links',
      'sitemap eligibility',
      'schema registry consistency',
    ],
    perPageChecks: [
      'rendered mobile/desktop visual review',
      'unique hero and quick answer',
      'FAQ parity with visible content',
      'CTA destination and wording',
      'visual asset relevance',
      'intent boundary review',
    ],
    antiTemplateDuplicationRules: [
      'Each page must open with its own user job and input/platform context.',
      'Use shared product workflow structure but page-specific examples, FAQ, and boundaries.',
      'Do not copy the same hero promise across platform pages.',
      'Every page must explicitly state what it does not own.',
      'Run a manual diff on H1, title, quick answer, section headings, examples, and FAQs before release.',
    ],
    pipeline: {
      batchAPlanning: '20 demand candidates -> ownership -> cannibalization -> 10 approved briefs',
      batchBProduction: 'up to 10 briefs -> content -> Product Truth -> visuals -> page registry -> planning_only/noindex_review',
      batchCReview: 'content readiness -> rendered review -> noindex_review',
      batchDRelease: 'approval -> indexable_approved -> release gate -> build -> prerender -> dist sync -> local commit -> Gemini push -> Coolify -> live gate -> visual check',
    },
    approvalRule: 'Planning and indexation approval must remain separate steps.',
  },
};

export const getFirstSeoPageProductionWavePlan = () => FIRST_SEO_PAGE_PRODUCTION_WAVE_2026_07_13;
